export const artists = [
  
    {
      id: 1,
      name: "Taco Hemingway",
      link: "taco-hemingway",
      href: "https://open.spotify.com/artist/5SyGEPymt1G2uto47tVWvZ",
      albums: ["Marmur", "Pocztówka z WWA, lato ‘19", "Szprycer", "Europa"],
      albumCount: 4,
      pfp: "/artists/taco-hemingway/pfp.jpg",
      banner: "/artists/taco-hemingway/bg.jpg",
      label: "2020",
      isVerified: true,
      rank: 3,
      description: "Mocny zawodnik wąsacz piwko wwa",
      followersCount: "3 475 211",
      monthlyListeners: "5 213 591",
    },

    {
      id: 1,
      name: "Oki",
      link: "oki",
      href: "https://open.spotify.com/artist/5SyGEPymt1G2uto47tVWvZ",
      albums: ["ERA47", "PRODUKT47", "OIO", "47UNIVERSE"],
      albumCount: 4,
      pfp: "/artists/oki/pfp.jpg",
      banner: "/artists/oki/bg.jpg",
      label: "2020",
      isVerified: true,
      rank: 2,
      description: "Oki 47 47xtt to zostanie na wieki",
      followersCount: "47 744 774",
      monthlyListeners: "817 474 747",
    },
    {
      id: 2,
      name: "Quebonafide",
      link: "quebonafide",
      href: "https://open.spotify.com/artist/3nmyv5cvLtbPqUGTKIVgYJ",
      albums: ["Egzotyka", "Romantic Psycho", "Ezoteryka"],
      albumCount: 3,
      pfp: "https://link-to-quebo-pfp.jpg",
      banner: "https://link-to-quebo-banner.jpg",
      label: "QueQuality",
      isVerified: true,
      rank: 5,
      description: "Mochi lubi lego kasti 8 kobiet",
      followersCount: "2 173 784",
      monthlyListeners: "6 137 841",
    },
    {
      id: 3,
      name: "O.S.T.R.",
      link: "o.s.t.r",
      href: "https://open.spotify.com/artist/2a6cbH7i7jUEgsB6pk29K7",
      albums: ["Podróż zwana życiem", "Gniew", "Życie po śmierci"],
      albumCount: 3,
      pfp: "https://link-to-ostr-pfp.jpg",
      banner: "https://link-to-ostr-banner.jpg",
      label: "Asfalt Records",
    },
  
    // Zagraniczni artyści
    {
      id: 4,
      name: "Kendrick Lamar",
      link: "kendrick-lamar",
      href: "https://open.spotify.com/artist/2YZyLoL8N0Wb9xBt1NhZWg",
      albums: ["good kid, m.A.A.d city", "To Pimp a Butterfly", "DAMN.", "Mr. Morale & The Big Steppers"],
      albumCount: 4,
      pfp: "https://link-to-kendrick-pfp.jpg",
      banner: "https://link-to-kendrick-banner.jpg",
      label: "Top Dawg Entertainment",
    },
    {
      id: 5,
      name: "J. Cole",
      link: "j.-cole",
      href: "https://open.spotify.com/artist/6l3HvQ5sa6mXTsMTB19rO5",
      albums: ["2014 Forest Hills Drive", "KOD", "The Off-Season"],
      albumCount: 3,
      pfp: "https://link-to-jcole-pfp.jpg",
      banner: "https://link-to-jcole-banner.jpg",
      label: "Dreamville Records",
    },
    {
      id: 6,
      name: "Drake",
      link: "drake",
      href: "https://open.spotify.com/artist/3TVXtAsR1Inumwj472S9r4",
      albums: ["Take Care", "Nothing Was the Same", "Scorpion", "Certified Lover Boy"],
      albumCount: 4,
      pfp: "https://link-to-drake-pfp.jpg",
      banner: "https://link-to-drake-banner.jpg",
      label: "OVO Sound",
    },
  ];